POST http://localhost:8080/contact/sendemail
Content-Type: application/json
{
  "message":"junior@gmail.com",
  "name":"junior",
  "message":"Bonjour Saleka, j'aime votre site",
  "subject":"Salutation"
}
###